# Adapted from /usr/share/containers/containers.conf

[containers]

# Allow ping(8) without CAP_NET_ADMIN and CAP_NET_RAW
#
default_sysctls = [
  "net.ipv4.ping_group_range=0 2147483647",
]

# Run an init inside the container that forwards signals and reaps processes.
#
init = true

# TODO Use Docker's stronger seccomp profile?
# https://github.com/moby/profiles/blob/main/seccomp/default.json
#
# Path to the seccomp.json profile which is used as the default seccomp profile
# for the runtime.
#
#seccomp_profile = "/usr/share/containers/seccomp.json"

# Set timezone in container. Takes IANA timezones as well as "local",
# which sets the timezone in the container to match the host machine.
#
tz = "Europe/Berlin"

# Default way to create a USER namespace for the container.
# Options are:
#   `private` Create private USER Namespace for the container, without adding any UID mappings.
#   `host`    Share host USER Namespace with the container. Root in the container is mapped to the host user UID.
#   `auto`    Automatically create a USER namespace with a unique mapping.
#   `keep-id` Like `private`, but container UIDs are mapped to the host user's subordinate UIDs listed in `/etc/subuid`, and the current user's `UID:GID` are mapped to the same values in the container.
#   `no-map`  Like `keep-id`, but the current user's `UID:GID` does not map to any `UID:GID` inside the container.
#
userns = "keep-id"


[engine]

# Emit logs on each invocation of the compose command indicating that an
# external compose provider is being executed.
#
compose_warning_logs = false

# Default OCI runtime
#
#runtime = "runc"
runtime = "crun"
