---
- name: adding user ricardo to group libvirt
  user:
    name: ricardo
    groups: libvirt
    append: yes
  become: yes
  tags: ['zypper', 'kvm']

- name: Install KVM package patterns
  zypper:
    name:
      - kvm_server
      - kvm_tools
    type: pattern
    state: present
  tags: ['zypper', 'kvm']

- name: Install KVM package patterns
  zypper:
    name:
      - qemu-*
      - libvirt-daemon
      - kvm_stat
    state: present
  tags: ['zypper', 'kvm']

- name: Add custom KVM sysctl's
  copy:
    src: sysctl.d/kvm.conf
    dest: /etc/sysctl.d/kvm.conf
    owner: root
    group: root
    mode: 0644
  tags: ['kvm', 'sysctl']

- name: Configure /etc/qemu/bridge.conf
  lineinfile:
    path: /etc/qemu/bridge.conf
    line: "allow all"
  tags: ['kvm']

- name: Configure bridge-br0
  copy:
    src: NetworkManager/bridge-br0.nmconnection
    dest: /etc/NetworkManager/system-connections/bridge-br0.nmconnection
    owner: root
    group: root
    mode: 0600
  tags: ['kvm']

- name: Configure bridge-slave
  copy:
    src: NetworkManager/bridge-slave-enp62s0u1u2.nmconnection
    dest: /etc/NetworkManager/system-connections/bridge-slave-enp62s0u1u2.nmconnection
    owner: root
    group: root
    mode: 0600
  tags: ['kvm'] 

- name: Configure host-bridge
  copy:
    src: libvirt/host-bridge.xml
    dest: /etc/libvirt/qemu/networks/host-bridge.xml
    owner: root
    group: root
    mode: 0600
  tags: ['kvm'] 

- name: Autostart host-bridge.xml
  file:
    src: /etc/libvirt/qemu/networks/host-bridge.xml
    dest: /etc/libvirt/qemu/networks/autostart/host-bridge.xml
    state: link
    owner: root
    group: root
  tags: ['kvm'] 

- name: Check AppArmor status for dnsmasq
  command: "sudo aa-status --json"
  register: aa_status
  changed_when: false

- name: Set AppArmor to complain mode if not already in complain mode
  command: "aa-complain /usr/sbin/dnsmasq"
  when: "'\"dnsmasq\": \"complain\"' not in aa_status.stdout"
