---
- name: adding user ricardo to group libvirt
  user:
    name: ricardo
    groups: libvirt
    append: yes
  become: yes

- name: Install KVM package patterns
  zypper:
    name:
      - kvm_server
      - kvm_tools
    type: pattern
    state: present

- name: Install KVM packages
  zypper:
    name:
      - libvirt-daemon
      - kvm_stat
      - qemu-*
      - qemu-tools
      - virtiofsd
    state: present

- include_tasks: bridge.yml
