---
- name: Install Google key
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install Chrome repo
  zypper_repository:
    name: google-chrome
    repo: 'https://dl.google.com/linux/chrome/rpm/stable/x86_64'
    auto_import_keys: true

- name: Install Chrome packages
  zypper:
    name:
      - google-chrome-stable
    state: present
    update_cache: true
