---
- name: Install Docker packages
  zypper:
    name:
      - docker
      - docker-bash-completion
      - docker-buildx
      - docker-compose
      - docker-rootless-extras
    state: present
  tags: ['zypper', 'docker']

- name: Modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[\w](?!.*\b{{ item }}\b).*)"$'
    replace: '\1 {{ item }}"'
  with_items:
    - "cgroup_enable=memory"
    - "intel_iommu=on"
    - "iommu=pt"
  tags: ['docker']

- name: Enable Docker service
  systemd_service:
    name: docker
    enabled: true
    masked: no
    state: started
  tags: ['docker']
