---
- name: Install Docker packages
  zypper:
    name:
      - docker
      - docker-bash-completion
      - docker-buildx
      - docker-compose
      - docker-rootless-extras
    state: present

- name: Enable Docker service
  systemd_service:
    name: docker
    enabled: true
    masked: no
    state: started
