---
- name: Modify /etc/default/grub
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT="[\w](?!.*\b{{ item }}\b).*)"$'
    replace: '\1 {{ item }}"'
  with_items:
    - "cgroup_enable=memory"
    - "intel_iommu=on"
    - "iommu=pt"
    - "pcie_aspm=off"
  tags: ['grub']

- name: Disable suspend on close lid
  copy:
    src: systemd/nosuspendonlidclosed.conf
    dest: /etc/systemd/logind.conf.d/nosuspendonlidclosed.conf
    owner: root
    group: root
    mode: 0644
  tags: ['misc']

- name: Remove stupid blacklist for BSD UFS kernel module
  file:
    src: /dev/null
    dest: /usr/lib/modprobe.d/60-blacklist_fs-ufs.conf
    state: link
    force: true
  tags: ['ufs']
