---
- name: Disable suspend on close lid
  copy:
    src: systemd/nosuspendonlidclosed.conf
    dest: /etc/systemd/logind.conf.d/nosuspendonlidclosed.conf
    owner: root
    group: root
    mode: 0644
  tags: ['misc']

- name: Add custom sudo configuration
  copy:
    src: sudoers.d/custom
    dest: /etc/sudoers.d/custom
    owner: root
    group: root
    mode: 0600
  tags: ['misc']

- name: Remove stupid blacklist for BSD UFS kernel module
  file:
    path: /lib/modprobe.d/60-blacklist_fs-ufs.conf
    state: absent
