---
- name: Uninstall NVIDIA packages & SUSE Prime
  zypper:
    name:
      - nvidia-compute-G06
      - nvidia-gl-G06
      - nvidia-video-G06
      - openSUSE-repos-NVIDIA
    clean_deps: true
    state: absent

- name: Install nouveau
  zypper:
    name:
      - Mesa-dri-nouveau
      - xf86-video-nouveau
    state: present
    update_cache: true

