---
- name: Uninstall NVIDIA repos & SUSE Prime
  zypper:
    name:
      - openSUSE-repos-NVIDIA
      - suse-prime
    clean_deps: true
    state: absent
  tags: ['zypper']

- name: Install nouveau
  zypper:
    name:
      - Mesa-dri-nouveau
      - xf86-video-nouveau
    state: present
    update_cache: true
  tags: ['zypper']

