---
- name: Install NVIDIA repos & SUSE Prime
  zypper:
    name:
      - openSUSE-repos-NVIDIA
    state: present
  tags: ['zypper', 'nvidia']

- name: Install NVIDIA driver
  zypper:
    name:
      - nvidia-compute-G06
      - nvidia-gl-G06
      - nvidia-utils-G06
      - nvidia-video-G06
    disable_recommends: false
    update_cache: true
    state: present
  tags: ['zypper', 'nvidia']

# TODO: Run dracut -f
- name: Disable NVIDIA modeset
  lineinfile:
    create: yes
    path: /etc/modprobe.d/nvidia-drm-nomodeset.conf
    regexp: modeset
    line: 'options nvidia_drm modeset=1'
