---
- name: Disable PackageKit
  systemd_service:
    name: packagekit
    enabled: false
    masked: yes
    state: stopped
  tags: ['zypper']

- name: Install packages
  zypper:
    name:
      - avahi-utils
      - bind-utils
      - bridge-utils
      - bsdtar
      - cifs-utils
      - curl
      - dejavu-fonts
      - distrobox
      - e2fsprogs
      - ed
      - expect
      - fakeroot
      - git
      - gnome-extensions
      - gnome-tweaks
      - go1.21
      - ipmitool
      - jetbrains-mono-fonts
      - jq
      - keepassxc
      - libcap-progs
      - libva-utils
      - lsscsi
      - lshw
      - lsof
      - ltrace
      - lynx
      - make
      - mc
      - MozillaThunderbird
      - mozilla-nss-tools
      - mtr
      - nautilus-extension-nextcloud
      - nautilus-extension-sendto-blueman
      - nautilus-extension-tilix
      - netcat-openbsd
      - net-tools
      - nextcloud-desktop
      - nmap
      - patch
      - pigz
      - podman
      - openssl
      - opi
      - perl-Test-PerlTidy
      - python3-devel
      - python3-virtualenv
      - qemu-tools
      - rclone
      - rootlesskit
      - rpcbind
      - rpmconf
      - rsync
      - screen
      - sg3_utils
      - ShellCheck
      - smartmontools
      - socat
      - strace
      - subversion
      - tcpdump
      - telnet
      - tilix
      - traceroute
      - transmission-gtk
      - unzip
      - vim
      - virt-manager
      - virt-viewer
      - wget
      - whois
      - xfsprogs
      - xhost
      - xsel
      - zerofree
      - zip
      - zstd
    state: present
    update_cache: true
  tags: ['zypper']

- name: Install package patterns
  zypper:
    name:
      - container_runtime
      - devel_C_C++
      - fonts
      - laptop
      - multimedia
    type: pattern
    state: present
  tags: ['zypper']

- name: Uninstall packages
  zypper:
    name:
      - cups
    clean_deps: true
    state: absent
  tags: ['zypper']
