---
- name: Allow vendor change
  lineinfile:
    path: /etc/zypp/zypp.conf
    line: "solver.allowVendorChange = false"
    insertafter: "^# solver.allowVendorChange "
  tags: ['zypper']

- name: Install Packman repo
  zypper_repository:
    name: packman-essentials
    repo: 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/Essentials/'
    auto_import_keys: true
    autorefresh: true
    priority: 77
  tags: ['zypper', 'packman']

- name: Install Packman packages
  zypper:
    name:
      - ffmpeg
      - gstreamer-plugins-good
      - gstreamer-plugins-good-extra
      - gstreamer-plugins-bad
      - gstreamer-plugins-bad-codecs
      - gstreamer-plugins-ugly
      - gstreamer-plugins-ugly-codecs
      - gstreamer-plugins-libav
      - libavcodec
      - pipewire-aptx
      - vlc
      - vlc-codecs
    force: true
    state: present
  tags: ['zypper', 'packman']

- name: Install h264 packages
  zypper:
    name:
      - gstreamer-plugin-openh264
      - mozilla-openh264
    state: present
  tags: ['zypper', 'packman']
