---
- name: Install Slack key
  rpm_key:
    key: https://packagecloud.io/gpg.key
    state: present
  tags: ['zypper', 'slack']

- name: Install Slack repo
  zypper_repository:
    name: slack
    repo: 'https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64'
    auto_import_keys: true
  tags: ['zypper', 'slack']

- name: Install Slack packages
  zypper:
    name:
      - slack
    state: present
    update_cache: true
  tags: ['zypper', 'slack']
