---
- name: Install filesystems repo
  shell: zypper addrepo --priority 100 https://download.opensuse.org/repositories/filesystems/openSUSE_Tumbleweed/filesystems.repo
  args:
    creates: /etc/zypp/repos.d/filesystems.repo

- name: Install filesystems key
  rpm_key:
    key: https://download.opensuse.org/repositories/filesystems/openSUSE_Tumbleweed/repodata/repomd.xml.key
    state: present

- name: Install ZFS package
  zypper:
    name:
      - zfs
    state: present
    update_cache: true

# Ignore zfs on dracut as we don't use it on root and may conflict with the kernel
- name: Ignore zfs on dracut
  copy:
    src: files/88-zfs.conf
    dest: /etc/dracut.conf.d/88-zfs.conf
    owner: root
    group: root
    mode: 0644
