---
- name: Install zram packages
  zypper:
    name:
      - systemd-zram-service
    state: present

- name: Enable zramswap service
  systemd_service:
    name: zramswap
    enabled: true
    masked: no
    state: started
